// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// TODO use flutterfire configure to generate the file
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqd2irNo8qWOmPRy9RYJ1F4jDnYTawTk0',
    appId: '1:81037857892:web:506bd25e6c7d8be9a93b71',
    messagingSenderId: '81037857892',
    projectId: 'gamingportal-1345c',
    authDomain: 'gamingportal-1345c.firebaseapp.com',
    storageBucket: 'gamingportal-1345c.appspot.com',
    measurementId: 'G-0SH6G103ZQ',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4IWTCApEVkFP8x3E1JbdXKaUE6qn67qo',
    appId: '1:81037857892:android:912c5208c5938762a93b71',
    messagingSenderId: '81037857892',
    projectId: 'gamingportal-1345c',
    storageBucket: 'gamingportal-1345c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACESy55rMMBTdncUgEAEd0rB3nB4Vm_pc',
    appId: '1:81037857892:ios:5dc723b4e2aae07ca93b71',
    messagingSenderId: '81037857892',
    projectId: 'gamingportal-1345c',
    storageBucket: 'gamingportal-1345c.appspot.com',
    iosClientId: '81037857892-klme8g9mdfg0gu9522rtk9v8aslb112p.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACESy55rMMBTdncUgEAEd0rB3nB4Vm_pc',
    appId: '1:81037857892:ios:5dc723b4e2aae07ca93b71',
    messagingSenderId: '81037857892',
    projectId: 'gamingportal-1345c',
    storageBucket: 'gamingportal-1345c.appspot.com',
    iosClientId: '81037857892-klme8g9mdfg0gu9522rtk9v8aslb112p.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

}